version: '3.8'

services:
  edge-server:
    image: nginx:alpine
    container_name: eduos-edge-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - eduportal-cache:/var/cache/nginx
    networks:
      - eduos-net

volumes:
  eduportal-cache:

networks:
  eduos-net:
